all: bellissimo no 
bellissimo: bellissimo.o
			g++ -o bellissimo bellissimo.o
bellissimo.o: bellissimo.cpp 
			
			g++ -c bellissimo.cpp -pedantic -Wall -std=c++11

no:			no.o
			g++ -o no no.o 
no.o: 		no.cpp
			g++ -c no.cpp -pedantic -Wall -std=c++11