all: main generatore filtro checksum visualizzatore

main: 
	gcc -o main main.c

generatore: 
	gcc -o generatore generatore.c 

filtro: 
	gcc -o filtro filtro.c

checksum: 
	gcc -o checksum checksum.c

visualizzatore: 
	gcc -o visualizzatore visualizzatore.c 

clean: 
	rm -f main
	rm -f filtro
	rm -f generatore 
	rm -f checksum
	rm -f visualizzatore